### ISSUE TITLE
tools/fast_importer should take a compression_level argument

### ISSUE THREAD

**Issue by siddharthab** [google/containerregistry#26]
Right now, it defaults to compression level 9 (in `v2_2_image.FromTarball`) which is terribly slow. A more reasonable default or a configurable level will make it more usable.

**Comment by siddharthab** [comment]
@mattmoor

**Comment by mattmoor** [comment]
I'm not sure a lower level would help appreciably.  Python gzip is just tremendously slow.

We could consider making [this](https://github.com/google/containerregistry/blob/master/tools/fast_importer_.py#L47) take a kwarg to control whether compressed or uncompressed blobs are emitted (or both).  WDYT?

**Comment by siddharthab** [comment]
uncompressed vs compressed would be best, but on my cursory glance at the code, it looks like a non-trivial change to skip compression altogether.

**Comment by mattmoor** [comment]
Yeah, this is a little trickier than I thought, mostly because of how oriented the `DockerImage` interface is around having the layer digests, which we basically don't have or need.

The good news is that `FromTarball` already lazily generates the manifest, so if we are careful we should be able to extend the interface to achieve what you want.  My current thinking looks something like:
1. Extend `DockerImage` to expose a `diff_ids()` member that returns the list of `diff_ids` from the `config_file()` (which we can access without producing the `manifest()` in `FromTarball`.
1. Extend the `DockerImage` interface to allow fetching `uncompressed_blob` by `diff_id`.
1. When `v2_2_save.fast` is called to emit uncompressed stuff, then bypass [this loop](https://github.com/google/containerregistry/blob/master/client/v2_2/save_.py#L168) completely and have another that uses the above.

WDYT?

**Comment by siddharthab** [comment]
Looks like it should work.

**Comment by siddharthab** [comment]
What do you think about https://github.com/google/containerregistry/pull/28?

Not quite what we discussed but looks simpler and does only what's needed.

**Comment by mattmoor** [comment]
I believe this should be resolved by outlining the gzip entirely
